package content;

import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JLabel;
import java.awt.CardLayout;
import java.awt.Font;
import java.awt.Color;
import javax.swing.JTextField;



import javax.swing.JPasswordField;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.awt.event.ActionEvent;
import java.awt.Button;
import javax.swing.ImageIcon;
import java.awt.Toolkit;
import javax.swing.UIManager;
import java.awt.Cursor;
import javax.swing.JMenuBar;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

public class Telas {

	private JFrame frmGcApartamentos;
	private JTextField textField;
	private JPasswordField passwordField;
	private JButton btnEntrar;
	private JPanel panel_2;
	private JPanel panel_4;
	private JPanel panel_5;
	private JPanel panel_6;
	private JPanel panel_7;
	

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					Telas window = new Telas();
					window.frmGcApartamentos.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the application.
	 */
	public Telas() {
		initialize();
	}

	/**
	 * Initialize the contents of the frame.
	 */
	private void initialize() {
		
		File dir = new File("NovaPasta");
		dir.mkdir();
		
		File arquivo = new File("NovaPasta/Agendamentos.txt");
		File l = new File("NovaPasta/login.txt");
		
		String usuariovalido[] = new String[2];
		try {
			arquivo.createNewFile();
			l.createNewFile();
			
			
		} catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		
		frmGcApartamentos = new JFrame();
		frmGcApartamentos.setIconImage(Toolkit.getDefaultToolkit().getImage(Telas.class.getResource("/images/logoCG.ico")));
		frmGcApartamentos.setTitle("GC APARTAMENTOS");
		frmGcApartamentos.setBounds(100, 100, 450, 300);
		frmGcApartamentos.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frmGcApartamentos.getContentPane().setLayout(new CardLayout(0, 0));
		
		JPanel panel = new JPanel();
		frmGcApartamentos.getContentPane().add(panel, "name_134947190415600");
		panel.setLayout(new CardLayout(0, 0));
		
		JPanel panel_1 = new JPanel();
		panel_1.setBackground(Color.WHITE);
		panel.add(panel_1, "name_135230858490899");
		panel_1.setLayout(null);
		
		JLabel lblNewLabel = new JLabel("Login");
		lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 16));
		lblNewLabel.setBounds(184, 72, 52, 28);
		panel_1.add(lblNewLabel);
		
		JLabel lblNewLabel_1 = new JLabel("Usu\u00E1rio");
		lblNewLabel_1.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblNewLabel_1.setBounds(44, 122, 59, 14);
		panel_1.add(lblNewLabel_1);
		
		JLabel lblNewLabel_2 = new JLabel("Senha");
		lblNewLabel_2.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblNewLabel_2.setBounds(44, 171, 46, 14);
		panel_1.add(lblNewLabel_2);
		
		textField = new JTextField();
		textField.setBounds(127, 121, 192, 20);
		panel_1.add(textField);
		textField.setColumns(10);
		
		passwordField = new JPasswordField();
		passwordField.setBounds(127, 170, 192, 20);
		panel_1.add(passwordField);
		
		btnEntrar = new JButton("Entrar");
		btnEntrar.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				
					try {
					
					FileReader fr = new FileReader(l);
					BufferedReader br = new BufferedReader(fr);
					String percorre;
					
					while((percorre = br.readLine()) != null ){
						String arraylogin[] = new String[2];
						arraylogin = percorre.split(" ");
						String passw = String.valueOf(passwordField.getPassword());
						//System.out.println("Your HashCode Generated by MD5 is: " + Criptografia.getMd5(passw));
						
						if(textField.getText().equals(arraylogin[0]) && Cript.getMd5(passw).equals(arraylogin[1])){
							usuariovalido[0] = arraylogin[0];
							usuariovalido[1] = arraylogin[1];
							panel_2.setVisible(true);
							panel_1.setVisible(false);
						}else {
							
						}
					}
					br.close();
					fr.close();
						
					}
				 catch (IOException e1) {
					// TODO Auto-generated catch block
					 System.out.println("Erro");
					e1.printStackTrace();
				}
			}
		});
		btnEntrar.setBounds(184, 214, 89, 23);
		panel_1.add(btnEntrar);
		
		JLabel lblNewLabel_4 = new JLabel("");
		lblNewLabel_4.setIcon(new ImageIcon(Telas.class.getResource("/images/logo3.jpg")));
		lblNewLabel_4.setBounds(0, 0, 434, 61);
		panel_1.add(lblNewLabel_4);
		
		JLabel lblNewLabel_5 = new JLabel("");
		lblNewLabel_5.setIcon(new ImageIcon(Telas.class.getResource("/images/1499345621-contact_85338 (3).png")));
		lblNewLabel_5.setBounds(337, 120, 31, 16);
		panel_1.add(lblNewLabel_5);
		
		JLabel lblNewLabel_6 = new JLabel("");
		lblNewLabel_6.setIcon(new ImageIcon(Telas.class.getResource("/images/1499345622-lock_85335 (2).png")));
		lblNewLabel_6.setBounds(337, 171, 46, 20);
		panel_1.add(lblNewLabel_6);
		
		panel_2 = new JPanel();
		panel_2.setBackground(Color.WHITE);
		panel.add(panel_2, "name_172632954438400");
		panel_2.setLayout(null);
		
		JLabel lblNewLabel_3 = new JLabel("Condom\u00EDnios");
		lblNewLabel_3.setFont(new Font("Tahoma", Font.BOLD, 11));
		lblNewLabel_3.setBounds(17, 45, 85, 22);
		panel_2.add(lblNewLabel_3);
		
		JButton btnVoltaLogin = new JButton("Voltar ao Login");
		btnVoltaLogin.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				
				limpar();
				panel_1.setVisible(true);
				panel_2.setVisible(false);
			}
		});
		btnVoltaLogin.setBounds(302, 221, 122, 29);
		panel_2.add(btnVoltaLogin);
		
		JButton btnNewButton = new JButton("");
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				panel_7.setVisible(true);
				panel_2.setVisible(false);
			}
		});
		btnNewButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		btnNewButton.setBorder(null);
		btnNewButton.setForeground(Color.WHITE);
		btnNewButton.setBackground(Color.WHITE);
		btnNewButton.setIcon(new ImageIcon(Telas.class.getResource("/images/image (3).jpg")));
		btnNewButton.setBounds(321, 92, 109, 87);
		panel_2.add(btnNewButton);
		
		JButton btnNewButton_1 = new JButton("");
		btnNewButton_1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				panel_4.setVisible(true);
				panel_2.setVisible(false);
			}
		});
		btnNewButton_1.setBorder(null);
		btnNewButton_1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		btnNewButton_1.setForeground(Color.WHITE);
		btnNewButton_1.setBackground(Color.WHITE);
		btnNewButton_1.setIcon(new ImageIcon(Telas.class.getResource("/images/condominio.png")));
		btnNewButton_1.setBounds(17, 92, 90, 80);
		panel_2.add(btnNewButton_1);
		
		JButton btnNewButton_2 = new JButton("");
		btnNewButton_2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		btnNewButton_2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				panel_5.setVisible(true);
				panel_2.setVisible(false);
			}
		});
		btnNewButton_2.setBackground(Color.WHITE);
		btnNewButton_2.setBorder(null);
		btnNewButton_2.setIcon(new ImageIcon(Telas.class.getResource("/images/edificio.png")));
		btnNewButton_2.setBounds(127, 84, 95, 95);
		panel_2.add(btnNewButton_2);
		
		JButton btnNewButton_3 = new JButton("");
		btnNewButton_3.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		btnNewButton_3.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				panel_6.setVisible(true);
				panel_2.setVisible(false);
			}
		});
		btnNewButton_3.setIcon(new ImageIcon(Telas.class.getResource("/images/apart.png")));
		btnNewButton_3.setBorder(null);
		btnNewButton_3.setBackground(Color.WHITE);
		btnNewButton_3.setBounds(217, 78, 103, 109);
		panel_2.add(btnNewButton_3);
		
		JLabel lblNewLabel_7 = new JLabel("Edif\u00EDcios");
		lblNewLabel_7.setFont(new Font("Tahoma", Font.BOLD, 11));
		lblNewLabel_7.setBounds(152, 49, 54, 14);
		panel_2.add(lblNewLabel_7);
		
		JLabel lblNewLabel_8 = new JLabel("Apartamentos");
		lblNewLabel_8.setFont(new Font("Tahoma", Font.BOLD, 11));
		lblNewLabel_8.setBounds(236, 49, 84, 14);
		panel_2.add(lblNewLabel_8);
		
		JLabel lblNewLabel_9 = new JLabel("Moradores");
		lblNewLabel_9.setFont(new Font("Tahoma", Font.BOLD, 11));
		lblNewLabel_9.setBounds(340, 49, 67, 14);
		panel_2.add(lblNewLabel_9);
		
		JButton btnNewButton_4 = new JButton("Sair");
		btnNewButton_4.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				
				System.exit(0);
			}
		});
		btnNewButton_4.setBounds(17, 224, 89, 23);
		panel_2.add(btnNewButton_4);
		
		JMenuBar menuBar = new JMenuBar();
		menuBar.setBounds(0, 0, 434, 22);
		panel_2.add(menuBar);
		
		JMenu mnNewMenu = new JMenu("Arquivo");
		menuBar.add(mnNewMenu);
		
		JMenuItem mntmNewMenuItem = new JMenuItem("Sair");
		mntmNewMenuItem.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				
				System.exit(0);
			}
		});
		mnNewMenu.add(mntmNewMenuItem);
		
		panel_4 = new JPanel();
		panel.add(panel_4, "name_221349437703500");
		panel_4.setLayout(null);
		
		JLabel lblNewLabel_10 = new JLabel("Condom\u00EDnios");
		lblNewLabel_10.setFont(new Font("Tahoma", Font.BOLD, 16));
		lblNewLabel_10.setBounds(170, 11, 111, 14);
		panel_4.add(lblNewLabel_10);
		
		JButton btnNewButton_6 = new JButton("Voltar");
		btnNewButton_6.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				panel_2.setVisible(true);
				panel_4.setVisible(false);
			}
		});
		btnNewButton_6.setBounds(10, 227, 89, 23);
		panel_4.add(btnNewButton_6);
		
		panel_5 = new JPanel();
		panel.add(panel_5, "name_221754501111600");
		panel_5.setLayout(null);
		
		JLabel lblNewLabel_11 = new JLabel("Edif\u00EDcios");
		lblNewLabel_11.setFont(new Font("Tahoma", Font.BOLD, 16));
		lblNewLabel_11.setBounds(191, 11, 74, 14);
		panel_5.add(lblNewLabel_11);
		
		JButton btnNewButton_5 = new JButton("Voltar");
		btnNewButton_5.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				panel_2.setVisible(true);
				panel_5.setVisible(false);
			}
		});
		btnNewButton_5.setBounds(10, 227, 89, 23);
		panel_5.add(btnNewButton_5);
		
		panel_6 = new JPanel();
		panel.add(panel_6, "name_222481303729500");
		panel_6.setLayout(null);
		
		JLabel lblNewLabel_12 = new JLabel("Apartamentos");
		lblNewLabel_12.setFont(new Font("Tahoma", Font.BOLD, 16));
		lblNewLabel_12.setBounds(143, 11, 124, 20);
		panel_6.add(lblNewLabel_12);
		
		JButton btnNewButton_7 = new JButton("Voltar");
		btnNewButton_7.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				panel_2.setVisible(true);
				panel_6.setVisible(false);
			}
		});
		btnNewButton_7.setBounds(10, 227, 89, 23);
		panel_6.add(btnNewButton_7);
		
		panel_7 = new JPanel();
		panel.add(panel_7, "name_222756029361300");
		panel_7.setLayout(null);
		
		JLabel lblNewLabel_13 = new JLabel("Moradores");
		lblNewLabel_13.setFont(new Font("Tahoma", Font.BOLD, 16));
		lblNewLabel_13.setBounds(168, 11, 113, 14);
		panel_7.add(lblNewLabel_13);
		
		JButton btnNewButton_8 = new JButton("Voltar");
		btnNewButton_8.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				panel_2.setVisible(true);
				panel_7.setVisible(false);
			}
		});
		btnNewButton_8.setBounds(10, 227, 89, 23);
		panel_7.add(btnNewButton_8);
	}
	
	private void limpar()
	{
	     textField.setText("");
	     passwordField.setText("");
	   
	}
}
