package content;

import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JLabel;
import java.awt.CardLayout;
import java.awt.Font;
import java.awt.Color;
import javax.swing.JTextField;



import javax.swing.JPasswordField;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.awt.event.ActionEvent;
import java.awt.Button;
import javax.swing.ImageIcon;
import java.awt.Toolkit;

public class Telas {

	private JFrame frmGcApartamentos;
	private JTextField textField;
	private JPasswordField passwordField;
	private JButton btnEntrar;
	private JPanel panel_2;
	private JPanel panel_3;
	

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					Telas window = new Telas();
					window.frmGcApartamentos.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the application.
	 */
	public Telas() {
		initialize();
	}

	/**
	 * Initialize the contents of the frame.
	 */
	private void initialize() {
		
		File dir = new File("NovaPasta");
		dir.mkdir();
		
		File arquivo = new File("NovaPasta/Agendamentos.txt");
		File l = new File("NovaPasta/login.txt");
		
		String usuariovalido[] = new String[2];
		try {
			arquivo.createNewFile();
			l.createNewFile();
			
			
		} catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		
		frmGcApartamentos = new JFrame();
		frmGcApartamentos.setIconImage(Toolkit.getDefaultToolkit().getImage(Telas.class.getResource("/images/logoCG.ico")));
		frmGcApartamentos.setTitle("GC APARTAMENTOS");
		frmGcApartamentos.setBounds(100, 100, 450, 300);
		frmGcApartamentos.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frmGcApartamentos.getContentPane().setLayout(new CardLayout(0, 0));
		
		JPanel panel = new JPanel();
		frmGcApartamentos.getContentPane().add(panel, "name_134947190415600");
		panel.setLayout(new CardLayout(0, 0));
		
		JPanel panel_1 = new JPanel();
		panel_1.setBackground(Color.WHITE);
		panel.add(panel_1, "name_135230858490899");
		panel_1.setLayout(null);
		
		JLabel lblNewLabel = new JLabel("Login");
		lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 16));
		lblNewLabel.setBounds(184, 72, 52, 28);
		panel_1.add(lblNewLabel);
		
		JLabel lblNewLabel_1 = new JLabel("Usu\u00E1rio");
		lblNewLabel_1.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblNewLabel_1.setBounds(44, 122, 59, 14);
		panel_1.add(lblNewLabel_1);
		
		JLabel lblNewLabel_2 = new JLabel("Senha");
		lblNewLabel_2.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblNewLabel_2.setBounds(44, 171, 46, 14);
		panel_1.add(lblNewLabel_2);
		
		textField = new JTextField();
		textField.setBounds(127, 121, 192, 20);
		panel_1.add(textField);
		textField.setColumns(10);
		
		passwordField = new JPasswordField();
		passwordField.setBounds(127, 170, 192, 20);
		panel_1.add(passwordField);
		
		btnEntrar = new JButton("Entrar");
		btnEntrar.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				
					try {
					
					FileReader fr = new FileReader(l);
					BufferedReader br = new BufferedReader(fr);
					String percorre;
					
					while((percorre = br.readLine()) != null ){
						String arraylogin[] = new String[2];
						arraylogin = percorre.split(" ");
						String passw = String.valueOf(passwordField.getPassword());
						//System.out.println("Your HashCode Generated by MD5 is: " + Criptografia.getMd5(passw));
						
						if(textField.getText().equals(arraylogin[0]) && Cript.getMd5(passw).equals(arraylogin[1])){
							usuariovalido[0] = arraylogin[0];
							usuariovalido[1] = arraylogin[1];
							panel_2.setVisible(true);
							panel_1.setVisible(false);
						}else {
							
						}
					}
					br.close();
					fr.close();
						
					}
				 catch (IOException e1) {
					// TODO Auto-generated catch block
					 System.out.println("Erro");
					e1.printStackTrace();
				}
			}
		});
		btnEntrar.setBounds(184, 214, 89, 23);
		panel_1.add(btnEntrar);
		
		JLabel lblNewLabel_4 = new JLabel("");
		lblNewLabel_4.setIcon(new ImageIcon(Telas.class.getResource("/images/logo3.jpg")));
		lblNewLabel_4.setBounds(0, 0, 434, 61);
		panel_1.add(lblNewLabel_4);
		
		JLabel lblNewLabel_5 = new JLabel("");
		lblNewLabel_5.setIcon(new ImageIcon(Telas.class.getResource("/images/1499345621-contact_85338 (3).png")));
		lblNewLabel_5.setBounds(337, 120, 31, 16);
		panel_1.add(lblNewLabel_5);
		
		JLabel lblNewLabel_6 = new JLabel("");
		lblNewLabel_6.setIcon(new ImageIcon(Telas.class.getResource("/images/1499345622-lock_85335 (2).png")));
		lblNewLabel_6.setBounds(337, 171, 46, 20);
		panel_1.add(lblNewLabel_6);
		
		panel_2 = new JPanel();
		panel.add(panel_2, "name_172632954438400");
		panel_2.setLayout(null);
		
		JLabel lblNewLabel_3 = new JLabel("Aqui come\u00E7a o Sistema !");
		lblNewLabel_3.setFont(new Font("Tahoma", Font.BOLD, 18));
		lblNewLabel_3.setBounds(102, 120, 249, 22);
		panel_2.add(lblNewLabel_3);
		
		JButton btnVoltaLogin = new JButton("Voltar ao Login");
		btnVoltaLogin.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				
				limpar();
				panel_1.setVisible(true);
				panel_2.setVisible(false);
			}
		});
		btnVoltaLogin.setBounds(321, 221, 103, 29);
		panel_2.add(btnVoltaLogin);
	}
	
	private void limpar()
	{
	     textField.setText("");
	     passwordField.setText("");
	   
	}
}
